version: 2

jobs:
    build:
        docker:
            #- image: "cimg/base:2020.01"
            - image: "ubuntu:devel"
        steps:
            - checkout
            - run:
                name: Updating apt and install git
                command: 'apt-get update && apt-get install -y git'
            - run:
                name: "telling apt that we're not interactive"
                command: 'export DEBIAN_FRONTEND=noninteractive'
            - run:
                name: Installing gcc g++
                command: 'apt-get install -y gcc g++ clang'
            - run:
                name: Installing cmake
                command: 'apt-get install -y cmake'
            - run:
                name: Installing boost threads
                command: 'apt-get install -y libboost-thread-dev'
            - run:
                name: Installing numerical libs
                command: 'apt-get install -y libeigen3-dev libblas-dev liblapack-dev'
            - run:
                name: Installing graphics libs
                command: 'apt-get install -y libglfw3-dev libgl-dev libpng++-dev libxinerama-dev xorg-dev'
            - run:
                name: Making CMake build files
                command: 'cmake -H. -Bbuild -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE="Debug"'
            - run:
                name: Building 
                command: 'cmake --build build -j 2'
            - run:
                name: Run tests
                command: 'cmake --build build --target test'
            - run:
                name: Quiting before doing cmake because libc++ does not currently have ranges and mtao should build around backcompat better
                command: circleci-agent step halt

            - run:
                name: Making CMake build files
                command: 'cmake -H. -Bbuild-clang -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang'
            - run:
                name: Building with clang
                command: 'cmake --build build-clang -j 2'
            - run:
                name: Run tests with clang
                command: 'cmake --build build-clang --target test'
