version: 2

jobs:
    build:
        docker:
            - image: "ubuntu:devel"
        steps:
            - checkout
            - run:
                name: Updating apt and install git
                command: 'apt-get update && apt-get install -y git'
            - run:
                name: Installing gcc
                command: 'apt-get install -y gcc'
            - run:
                name: Installing cmake
                command: 'apt-get install -y cmake'
            - run:
                name: Installing boost threads
                command: 'apt-get install -y libboost-thread-dev'
            - run:
                name: Installing numerical libs
                command: 'apt-get install -y libeigen3-dev libblas-dev liblapack-dev'
            - run:
                name: Installing graphics libs
                command: 'apt-get install -y libglfw3-dev libgl-dev libpng++-dev libxinerama-dev xorg-dev'
            - run:
                name: Making CMake build files
                command: 'cmake -H. -Bbuild -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE="Release"'
            - run:
                name: Building 
                command: 'cmake --build build -j 2'
                #- persist_to_workspace:
                #    root: workspace
                #    test:
                #        docker:
                #            - image: "ubuntu:devel"
                #            - image: "gcc:9.2.0"
                #        steps:
            - run:
                name: Run tests
                command: 'cmake --build build --target test'


                #workflows:
                #  version: 2
                #  build_and_test:
                #    jobs:
                #      - build
                #      - test:
                #          requires:
                #            - build
